### ISSUE TITLE
Service name, Logo and Favicon

### ISSUE THREAD

**Issue by tamaki-osamu** [tamaki-osamu/tide-graph#2]
## Task

Decide service name, logo and Favicon

### To Do

- [ ] decide service name
- [ ] decide logo design
- [ ] decide favicon design
- [ ] make a logo
- [ ] make a favicon

### Other information

none
